on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: vuestorefront/publish-docs-action@v1
        with:
          image: 'image'
          path: 'path'
          port: 'port'
          has-base-path: false
          user-id: 'userid'
          api-key: 'apikey'
          name: 'name'
          tag: 'tag'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
