on: [push]

jobs:
  publish_vsf_docs_job:
    runs-on: ubuntu-latest
    name: Publish VSF doc
    steps:
      - name: Publish VSF doc
        id: publish
        uses: vuestorefront/publish-docs-action@main
        with:
          user-id: ${{ secrets.DOCS_CLOUD_USERNAME }}
          api-key: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          name: 'name'
          tag: 'tag'
          image: 'image'
          path: 'path'
          port: 'port'
          has-base-path: false
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
